apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-depl
  template:
    metadata:
      labels:
        app: client-depl
    spec:
      containers:
        - name: client-depl
          image: cbanchio5/client-depl

---
apiVersion: v1
kind: Service
metadata:
  name: client-depl-srv
spec:
  selector:
    app: client-depl
  ports:
    - name: client-depl
      protocol: TCP
      port: 3000
      targetPort: 3000
